[package]
name = "kouhu"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["@Harry-Chen"]
license = "MIT"
description = "Chinese lipsum text generator; 中文乱数假文（Lorem Ipsum）生成"
repository = "https://github.com/Harry-Chen/kouhu"
categories = ["utility"]
keywords = ["lorem", "lorem ipsum", "lipsum", "dummy text", "blind text", "placeholder", "chinese"]
exclude = ["test/*", "docs/*"]
